createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: job
    selector:
      query:  "true"
    port:
      entity:
        mappings:
          identifier: 'if .url | contains("://") then (.url | split("://")[1] | sub("^.*?/"; "")) else .url end | sub("%20"; "-"; "g") | sub("/"; "-"; "g") | .[:-1]'
          title: .displayName
          blueprint: '"job"'
          properties:
            jobName: .fullName
            url: '.url | if test("://") then sub("^[^/]+//[^/]+"; "") else . end'
            jobStatus: '.color as $input | if $input == "notbuilt" then "created" else "updated" end'
            timestamp: .time
  - kind: build
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.fullDisplayName | sub(" "; "-"; "g") | sub("#"; ""; "g")'
          title: .displayName
          blueprint: '"build"'
          properties:
            buildStatus: .result
            buildUrl: '.url | if test("://") then sub("^[^/]+//[^/]+"; "") else . end'
            buildDuration: .duration
            timestamp: '.timestamp as $input | if $input | type == "number" then ($input / 1000 | todate) else $input end'
          relations:
            job: '.url as $input | if $input | contains("://") then ($input | split("://")[1] | sub("^.*?/"; "")) else $input end | tostring | sub("%20"; "-"; "g") | sub("/"; "-"; "g") | .[:-1] | sub("-[0-9]+$"; "")'
