createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: job
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .name | sub(" "; "-"; "g")
          title: .displayName
          blueprint: '"jenkinsJob"'
          properties:
            jobName: .fullName
            url: .url
            jobStatus: '.color as $c | {"notbuilt": "created", "blue": "passing", "red": "failing"}[$c // "updated"]'
            timestamp: .time
          relations:
            jobs: '. as $body | $body.jobs | map($body.name + " " + .name  | sub(" "; "-"; "g")) '
  - kind: build
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.__jobName + "-" + .id | sub(" "; "-"; "g")'
          title: .displayName
          blueprint: '"jenkinsBuild"'
          properties:
            buildStatus: .result
            buildUrl: .url
            buildDuration: .duration
            timestamp: '.timestamp / 1000 | todate'
          relations:
            parentJob: '.__jobName | sub(" "; "-"; "g")'
